In [1]:
import pandas as pd

In [2]:
con = "postgresql://postgesql:qwer1234@localhost:5432/postgesql"

In [4]:
pd.read_sql_query("""
SELECT * FROM information_schema.tables
""", con)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,postgesql,pg_catalog,pg_statistic,BASE TABLE,None,None,None,None,None,YES,NO,None
1,postgesql,pg_catalog,pg_type,BASE TABLE,None,None,None,None,None,YES,NO,None
2,postgesql,pg_catalog,pg_foreign_table,BASE TABLE,None,None,None,None,None,YES,NO,None
3,postgesql,pg_catalog,pg_authid,BASE TABLE,None,None,None,None,None,YES,NO,None
4,postgesql,pg_catalog,pg_shadow,VIEW,None,None,None,None,None,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
208,postgesql,information_schema,foreign_table_options,VIEW,None,None,None,None,None,NO,NO,None
209,postgesql,information_schema,foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
210,postgesql,information_schema,_pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None
211,postgesql,information_schema,user_mapping_options,VIEW,None,None,None,None,None,NO,NO,None
212,postgesql,information_schema,user_mappings,VIEW,None,None,None,None,None,NO,NO,None

In [5]:
df = pd.read_json('https://github.com/storemesh/masterdata/raw/refs/heads/main/master_area_th.json')
df

,AD_LEVEL,TA_ID,TAMBON_T,TAMBON_E,AM_ID,AMPHOE_T,AMPHOE_E,CH_ID,CHANGWAT_T,CHANGWAT_E,LAT,LONG
0,4,910106,ต. เกาะสาหร่าย,Ko Sarai,9101,None,Mueang Satun,91,จ. สตูล,Satun,6.546,99.706
1,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.646,101.171
2,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.645,101.170
3,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.649,101.174
4,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.644,101.169
...,...,...,...,...,...,...,...,...,...,...,...,...
7763,4,710803,ต. ไล่โว่,Lai Wo,7108,อ. สังขละบุรี,Sangkhla Buri,71,จ. กาญจนบุรี,Kanchanaburi,15.345,98.664
7764,4,710705,ต. ชะแล,Chalae,7107,อ. ทองผาภูมิ,Thong Pha Phum,71,จ. กาญจนบุรี,Kanchanaburi,14.996,98.833
7765,4,610607,ต. แก่นมะกรูด,Kaen Makrut,6106,อ. บ้านไร่,Ban Rai,61,จ. อุทัยธานี,Uthai Thani,15.292,99.168
7766,4,630805,ต. แม่ละมุ้ง,Mae Lamung,6308,อ. อุ้มผาง,Um Phang,63,จ. ตาก,Tak,15.641,98.966
7767,4,630305,ต. บ้านนา,Ban Na,6303,อ. สามเงา,Sam Ngao,63,จ. ตาก,Tak,17.333,98.864

In [6]:
df.to_sql('dim_area', con=con, index=False)

768

In [7]:
import psycopg2

In [8]:
conn = psycopg2.connect(con)
conn

In [9]:
cur = conn.cursor()

In [10]:
cur.execute("""
TRUNCATE TABLE dim_area
""")

In [11]:
conn.commit()

In [14]:
pd.read_sql_query("""
SELECT * FROM dim_area
""",con)

,AD_LEVEL,TA_ID,TAMBON_T,TAMBON_E,AM_ID,AMPHOE_T,AMPHOE_E,CH_ID,CHANGWAT_T,CHANGWAT_E,LAT,LONG
0,4,910106,ต. เกาะสาหร่าย,Ko Sarai,9101,None,Mueang Satun,91,จ. สตูล,Satun,6.546,99.706
1,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.646,101.171
2,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.645,101.170
3,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.649,101.174
4,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.644,101.169
...,...,...,...,...,...,...,...,...,...,...,...,...
7763,4,710803,ต. ไล่โว่,Lai Wo,7108,อ. สังขละบุรี,Sangkhla Buri,71,จ. กาญจนบุรี,Kanchanaburi,15.345,98.664
7764,4,710705,ต. ชะแล,Chalae,7107,อ. ทองผาภูมิ,Thong Pha Phum,71,จ. กาญจนบุรี,Kanchanaburi,14.996,98.833
7765,4,610607,ต. แก่นมะกรูด,Kaen Makrut,6106,อ. บ้านไร่,Ban Rai,61,จ. อุทัยธานี,Uthai Thani,15.292,99.168
7766,4,630805,ต. แม่ละมุ้ง,Mae Lamung,6308,อ. อุ้มผาง,Um Phang,63,จ. ตาก,Tak,15.641,98.966
7767,4,630305,ต. บ้านนา,Ban Na,6303,อ. สามเงา,Sam Ngao,63,จ. ตาก,Tak,17.333,98.864